
Size (sqft)	    Number of Bedrooms	    Number of floors	    Age of Home	        Price (1000s dollars)
2104	        5	                    1	                    45	                460
1416	        3	                    2	                    40	                232
852	            2	                    1	                    35	                178


In [13]:
import matplotlib as plt
import numpy as np

#Data
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

#Show Data
print(f"Data of X_train: \n{X_train}")
print(f"Data of y_train: \n{y_train}")

Data of X_train: 
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Data of y_train: 
[460 232 178]
3


Initial value of w and b (we choose it by ourselves)

In [4]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


predict function without using dot

In [8]:
def predict_single_loop(x, w, b):
    n = x.shape[0]
    predict_val = 0
    for i in range(n):
        predict_val += x[i]*w[i]
    predict_val += b
    return predict_val

predicting test

In [9]:
predict_test_val = predict_single_loop(X_train[0,:], w_init, b_init)
print(f"predicted value is: {predict_test_val}")

predicted value is: 459.9999976194083


Single prediction function using dot

In [10]:
def predict(x, w, b):
    return np.dot(x, w) + b

Test

In [11]:
predict_val = predict(X_train[0,:], w_init, b_init)
print(f"predicted value is: {predict_val}")

predicted value is: 459.9999976194083


develop Cost Funtion to compute cost

In [15]:
def compute_cost(X, y, w, b):
    #number of sample
    m = y.shape[0]
    cost = 0
    for i in range(m):
        different = predict(X[i,:], w, b) - y[i]
        different_square = different**2
        cost += different_square
    cost/=2*m
    return cost

    


Test cost

In [19]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f"cost value is: {cost}")

cost value is: 1.5578904428966628e-12


Compute gradient descent

In [31]:
def compute_gradient(x, y, w, b):
    m = x.shape[0]
    n = x.shape[1]
    dj_dw = np.zeros((n))
    dj_db = 0.0
    for i in range(m):
        f_wb_i = np.dot(x[i,:],w) + b
        err = f_wb_i - y[i]
        for j in range(n):
            dj_dw[j] += err * x[i, j]
        dj_db += err
    dj_dw /= m
    dj_db /= m
    return dj_dw, dj_db


Test

In [32]:
#Compute and display gradient 
tmp_dj_dw, tmp_dj_db = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')
print(f'dj_db at initial w,b: {tmp_dj_db}')

dj_dw at initial w,b: 
 [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]
dj_db at initial w,b: -1.6739251501955248e-06


Gradient Descent

In [39]:
def gradient_descent(x, y, w, b, alpha, num):
    w_train = w
    b_train = b
    w_temp = w
    b_temp = b
    J_hist = []
    J_hist.append(compute_cost(x,y,w,b))
    for number in range(num):
        dj_dw, dj_db = compute_gradient(x, y, w_train, b_train)
        w_temp = w_train - alpha*dj_dw
        b_temp = b_train - alpha*dj_db
        w_train = w_temp
        b_train = b_temp
        J_hist.append(compute_cost(x,y,w_train,b_train))
        if (number % 100 == 0):
            print(f"Cost at {number}: {J_hist[-1]}")
    return w_train, b_train, J_hist


Test

In [40]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
alpha = 5.0e-7
ite = 1000
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b, 
                                                    alpha, ite)
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Cost at 0: 2529.4629522316304
Cost at 100: 695.990315835203
Cost at 200: 694.9206979323061
Cost at 300: 693.8604297851192
Cost at 400: 692.8094286135915
Cost at 500: 691.7676123706057
Cost at 600: 690.7348997354997
Cost at 700: 689.711210107616
Cost at 800: 688.6964635999458
Cost at 900: 687.6905810327947
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
